[build]
  command = "jekyll build"
  publish = "_site"

[dev] 
  command = "bundle exec jekyll server --trace" # Command to start your dev server
  port = 4000 # Port that the dev server will be listening on
  publish = "_site" # Folder with the static content for _redirect file

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "http://alia-ressources.netlify.com/*"
  to = "http://ressources.aliapourvous.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/accueil"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/*"
  to = "https://aliapourvous.com/blog:splat"
  status = 301
  force = true

[[redirects]]
  from = "/a-propos*"
  to = "https://aliapourvous.com/a-propos"
  status = 301
  force = true

[[redirects]]
  from = "/contact*"
  to = "https://aliapourvous.com/contact"
  status = 301
  force = true